Library/Library/Models/Borrowing.cs
using Library.Areas.Identity.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Library.Models.Validation;

namespace Library.Models
{
    public class Borrowing
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public Book Book { get; set; }
        public string ApplicationUserId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }

        [Display(Name = "Start Date"), DataType(DataType.Date)]
        [DateBiggerThanOrEqualToToday]
        public DateTime StartDate { get; set; } = DateTime.Now.Date;

        [Display(Name = "Max Date"), DataType(DataType.Date)]
        [DateBiggerThanOrEqualToToday]
        public DateTime MaxDate { get; set; } = DateTime.Now.Date.AddDays(30);


        [Display(Name = "End Date"), DataType(DataType.Date)]
        public DateTime? EndDate { get; set; }

        [StringLength(500)]
        public string Description { get; set; }
    }
}

Library/Library/Controllers/BorrowingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library.Data;
using Library.Models;
using System.Security.Cryptography.X509Certificates;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;

namespace Library.Controllers
{
    [Authorize(Roles = "admin")]
    public class BorrowingsController : Controller
    {
        private readonly LibraryContext _context;

        public BorrowingsController(LibraryContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Statistic()
        {
            DateTime[] last7Days = Enumerable.Range(0, 7)
                                    .Select(i => DateTime.Now.Date.AddDays(-i))
                                    .ToArray();


            Dictionary<string, int> data = new Dictionary<string, int>();

            foreach (var i in last7Days) {
                data.Add(i.ToShortDateString(), _context.Borrowing.Where(b => b.StartDate == i).Count());
            }

            return Json(data);
        }

        // GET: Borrowings
        public async Task<IActionResult> Index()
        {
            var libraryContext = _context.Borrowing.Include(b => b.ApplicationUser).Include(b => b.Book);
            return View(await libraryContext.ToListAsync());
        }

        // GET: Borrowings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var borrowing = await _context.Borrowing
                .Include(b => b.ApplicationUser)
                .Include(b => b.Book)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (borrowing == null)
            {
                return NotFound();
            }

            return View(borrowing);
        }

        // GET: Borrowings/Create
        public IActionResult Create()
        {
            Borrowing borrowing = new Borrowing();
            borrowing.StartDate = DateTime.Now;
            borrowing.MaxDate = DateTime.Now.AddDays(30);
            ViewData["ApplicationUserId"] = new SelectList(_context.ApplicationUser, "Id", "UserName");

            var AllBooks = _context.Book.Include(b => b.Borrowing);

            List<Book> books = new List<Book>();

            foreach(Book b in AllBooks) {
                if (b.Borrowing.Any())
                {
                    if (b.Borrowing.Last().EndDate != null)
                    {
                        books.Add(b);
                    }
                }
                else {
                    books.Add(b);
                }
               
            }

         
            ViewData["BookId"] = new SelectList(books, "Id", "Title");
            return View(borrowing);
        }

        // POST: Borrowings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BookId,ApplicationUserId,StartDate,MaxDate,EndDate, Description")] Borrowing borrowing)
        {
            if (ModelState.IsValid)
            {
                _context.Add(borrowing);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.ApplicationUser, "Id", "UserName");
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "Title");
            return View(borrowing);
        }

        // GET: Borrowings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var borrowing = await _context.Borrowing.FindAsync(id);
            if (borrowing == null)
            {
                return NotFound();
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.ApplicationUser, "Id", "UserName", borrowing.ApplicationUserId);
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "Title", borrowing.BookId);
            return View(borrowing);
        }

        // POST: Borrowings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BookId,ApplicationUserId,StartDate,MaxDate,EndDate, Description")] Borrowing borrowing)
        {
            if (id != borrowing.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(borrowing);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BorrowingExists(borrowing.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.ApplicationUser, "Id", "UserName", borrowing.ApplicationUserId);
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "Title", borrowing.BookId);
            return View(borrowing);
        }

        // GET: Borrowings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var borrowing = await _context.Borrowing
                .Include(b => b.ApplicationUser)
                .Include(b => b.Book)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (borrowing == null)
            {
                return NotFound();
            }

            return View(borrowing);
        }

        // POST: Borrowings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var borrowing = await _context.Borrowing.FindAsync(id);
            _context.Borrowing.Remove(borrowing);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BorrowingExists(int id)
        {
            return _context.Borrowing.Any(e => e.Id == id);
        }
    }
}

Library/Library/Views/Borrowings/Create.cshtml
@model Library.Models.Borrowing

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Borrowing</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BookId" class="control-label"></label>
                <select asp-for="BookId" class="form-control" asp-items="ViewBag.BookId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationUserId" class="control-label"></label>
                <select asp-for="ApplicationUserId" class="form-control" asp-items="ViewBag.ApplicationUserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxDate" class="control-label"></label>
                <input asp-for="MaxDate" class="form-control" />
                <span asp-validation-for="MaxDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Library/Views/Borrowings/Delete.cshtml
@model Library.Models.Borrowing

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Borrowing</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaxDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaxDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Library/Library/Views/Borrowings/Details.cshtml
@model Library.Models.Borrowing

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Borrowing</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MaxDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MaxDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Library/Library/Views/Borrowings/Edit.cshtml
@model Library.Models.Borrowing

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Borrowing</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="BookId" class="control-label"></label>
                <select asp-for="BookId" class="form-control" asp-items="ViewBag.BookId"></select>
                <span asp-validation-for="BookId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationUserId" class="control-label"></label>
                <select asp-for="ApplicationUserId" class="form-control" asp-items="ViewBag.ApplicationUserId"></select>
                <span asp-validation-for="ApplicationUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxDate" class="control-label"></label>
                <input asp-for="MaxDate" class="form-control" />
                <span asp-validation-for="MaxDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Library/Views/Borrowings/Index.cshtml
@model IEnumerable<Library.Models.Borrowing>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Borrowings</h1>

<div id="chart"></div>
<div id="msg"></div>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Book)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.ApplicationUser)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.MaxDate)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Book.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationUser.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript">

    google.charts.load('current', { 'packages': ['corechart'], 'callback': drawCharts});

    function drawCharts() {
         var options = {};
    options.url = '@Url.Action("Statistic", "Borrowings")';
    options.type = "GET";
    options.dataType = "json";
    options.success = function (data) {

        var chartData = [
            ['Day', 'Counter']
        ];


        for (const [key, value] of Object.entries(data)) {
            chartData.push([key, parseInt(value)]);
        }

        var chartDataTable = google.visualization.arrayToDataTable(chartData);
        var chartOptions = {
            title: "Borrowings in this week",
            hAxis: {
                title: 'Counter',
                minValue: 0
            },
            vAxis: {
                title: 'Week Days'
            }
        };

        var chart = new google.visualization.PieChart
            (document.getElementById('chart'));
        chart.draw(chartDataTable, chartOptions);

    };

    options.error = function () {
        $("#msg").html("<h2>Error whileusing Google Charts!</h2>");
    };
    $.ajax(options);
    }
</script>